name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23 
      
      - name: Clean previous build output
        run: rm -rf dist

      - name: Clean node_modules and lockfile
        run: |
          rm -rf node_modules
          rm -f yarn.lock

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build 

      - name: Debug
        run: tree dist
      
      - name: Check dist contents
        run: ls -al dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /dist
